apiVersion: v1
data:
  application.yml: |
    spring:
      application:
        name: eureka-client
    server:
      port: 0
    eureka:
      client:
        registerWithEureka: true
        serviceUrl:
          defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      instance:
        preferIpAddress: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: client-application-properties
