server:
  port: 8761

spring:
  application:
    name: eureka
  security:
    user:
      name: admin
      password: pwd
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone:  http://admin:pwd@localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
