name: eureka

on:
  push:
    # branches:
    #   - "develop"
    tags:
      - "server-v*"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/yevgen-grytsay/eureka-server
          tags: |
            type=semver,prefix=server-,pattern={{version}}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.server
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
