name: eureka-server

on:
  push:
    # branches:
    #   - "develop"
    tags:
      - "server-v*"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    container:
      image: gradle:8.8.0-jdk17
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run tests
        run: ./gradlew clean test -info

  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: ci

    env:
      REGISTRY: ghcr.io

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/yevgen-grytsay/eureka-server
          tags: |
            type=match,pattern=server-v(.*),group=1
            type=semver,pattern={{version}}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.server
          platforms: linux/amd64
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    
      - uses: mikefarah/yq@v4.43.1
        with:
          cmd: yq -i '.image.tag=${{ steps.meta.outputs.version }}' helm/server/values.yaml
